optimize_resume_task:
  description: >
    Optimize a candidate's resume while preserving the original content and formatting. Ensure it aligns with the job description and is ATS-friendly.
  instructions: >
    1. Extract all key details (skills, experience, education) from the resume while **keeping the original structure intact**.
    2. Optimize the resume for ATS compatibility and **incorporate relevant keywords** from the job description.
    3. Ensure the resume remains **personalized** and not a generic example.
  key_objectives:
    - Keep the **user's original resume** structure.
    - Add **job-specific keywords** to improve ATS ranking.
    - Do not generate a **new template**; refine the existing content.
  expected_output: >
    The **original resume**, improved with ATS optimization and relevant job description keywords, while keeping the format intact.
  output_format: >
    - Section: [Original Resume with ATS Enhancements]
