name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4

      # Frontend: Next.js + TS + Tailwind
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Test Frontend
        working-directory: ./ElevateFrontend
        run: |
          npm ci
          npm run lint
          npm run type-check
          npm test -- --ci
          npm run build

      # Backend: FastAPI + Python + MongoDB
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install & Test Backend
        working-directory: ./ElevateBackend
        env:
          MONGODB_URI: mongodb+srv://dsnethma:eh2SrcppLJJYO6gP@elevatecluster.ao9i3.mongodb.net/?retryWrites=true&w=majority&appName=ElevateCluster
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          flake8 .
          mypy .
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Replace these echos with your real deploy commands
      - name: Deploy Frontend
        working-directory: ./ElevateFrontend
        run: echo "→ your Vercel/Netlify deploy here"

      - name: Deploy Backend
        working-directory: ./ElevateBackend
        run: echo "→ your Docker/Heroku/etc. deploy here"
